// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASJ8zafTi8fFikRmqcagEfKvhyQUg2LIE',
    appId: '1:211272924311:web:d613dd1faa63e2bd107dd2',
    messagingSenderId: '211272924311',
    projectId: 'social-hwebservices',
    authDomain: 'social-hwebservices.firebaseapp.com',
    storageBucket: 'social-hwebservices.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDve3dU15Q6kFOxl7qBjidNlZdrh0U3iug',
    appId: '1:211272924311:android:20d2c09d4ec47db9107dd2',
    messagingSenderId: '211272924311',
    projectId: 'social-hwebservices',
    storageBucket: 'social-hwebservices.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOyzRzj2-uxjKh5lIbqqgwIHoHQisdHSI',
    appId: '1:211272924311:ios:205369a5f24dc7e8107dd2',
    messagingSenderId: '211272924311',
    projectId: 'social-hwebservices',
    storageBucket: 'social-hwebservices.appspot.com',
    iosClientId: '211272924311-9cmkgvqd0o291pmol2lv9ri3n50dsgvq.apps.googleusercontent.com',
    iosBundleId: 'com.hwebservices.gbearwoof',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOyzRzj2-uxjKh5lIbqqgwIHoHQisdHSI',
    appId: '1:211272924311:ios:205369a5f24dc7e8107dd2',
    messagingSenderId: '211272924311',
    projectId: 'social-hwebservices',
    storageBucket: 'social-hwebservices.appspot.com',
    iosClientId: '211272924311-9cmkgvqd0o291pmol2lv9ri3n50dsgvq.apps.googleusercontent.com',
    iosBundleId: 'com.hwebservices.gbearwoof',
  );
}
