// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIALpuGjOWlDfLGUgZaDxh2EpCKAM4Myo',
    appId: '1:725587595838:web:e045c718de0ab09c5fb76f',
    messagingSenderId: '725587595838',
    projectId: 'social-30',
    authDomain: 'social-30.firebaseapp.com',
    storageBucket: 'social-30.appspot.com',
    measurementId: 'G-PKG5ZF0FB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATtCfLbJG-O5HXJ2yGrDZHYNM13coJrc0',
    appId: '1:725587595838:android:7bd932255a350e675fb76f',
    messagingSenderId: '725587595838',
    projectId: 'social-30',
    storageBucket: 'social-30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3rQ33stdNNJ78vJoZ1-1rY_V53-TG17c',
    appId: '1:725587595838:ios:db9ebe63226df0a85fb76f',
    messagingSenderId: '725587595838',
    projectId: 'social-30',
    storageBucket: 'social-30.appspot.com',
    iosClientId:
        '725587595838-gqru5olcblgbb2avhrg470cjildcuqbm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDatingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3rQ33stdNNJ78vJoZ1-1rY_V53-TG17c',
    appId: '1:725587595838:ios:2e4d6865697abaf35fb76f',
    messagingSenderId: '725587595838',
    projectId: 'social-30',
    storageBucket: 'social-30.appspot.com',
    iosClientId:
        '725587595838-3fff6j13ambhr9rlsmd92ecj6url3cmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.social',
  );
}
